task:
  container:
    image: gcc:latest
  build_script:
    - sh build.sh --auto-iar --auto-umber --kos --devices --devbranch core
  amd64_kos_artifacts:
    path: "bin/kos"
  amd64_device_artifacts:
    path: "bin/devices/*"

task:
  arm_container:
    image: gcc:latest
  build_script:
    - sh build.sh --auto-iar --auto-umber --kos --devices --devbranch core
  arm64_kos_artifacts:
    path: "bin/kos"
  arm64_device_artifacts:
    path: "bin/devices/*"
