# there aren't any artifacts here, because every component is meant to have its own CI setup

task:
  container:
    image: gcc:latest
  bob_script:
    - git clone https://github.com/inobulles/bob
    - ( cd bob && sh build.sh && sh-bin/bob install )
  build_script:
    - bob test install

task:
  arm_container:
    image: gcc:latest
  bob_script:
    - git clone https://github.com/inobulles/bob
    - ( cd bob && sh build.sh && sh-bin/bob install )
  build_script:
    - bob test install
