// install dependencies

Deps.git("https://github.com/inobulles/umber")
Deps.git("https://github.com/inobulles/iar")

// install components

Deps.git("https://github.com/inobulles/aqua-kos", "bob")

// running

class Runner {
	static run(args) {
		return File.exec("kos", args)
	}
}

// installation map
// since we don't really generate anything here, the installation map installs stuff generated by our dependencies

var install = {
	"kos": "%(OS.prefix())/bin/aqua",
}
